### ISSUE TITLE
maps2 v11 with OpenStreetMap

### ISSUE THREAD

**Issue by Hobokens** [jweiland-net/maps2#306]
TYPO3 12.4.9., maps2 11.0.0.

When using the OpenStreetMap option, I I can't `open info window`. In the console I have the error message:

```
OpenStreetMap2.js:468 
               
       POST https://dev.my-domain.de/testpage?tx_maps2_maps2%5Baction%5D=process&tx_maps2_maps2%5Bcontroller%5D=Ajax&tx_maps2_maps2%5Bmethod%5D=renderInfoWindowContent&type=1614075471&cHash=a1cc794bc1c13e3e2b1e96a9bc8fa2d7 500 (Internal Server Error)
(anonym) @ OpenStreetMap2.js:468
fire @ leaflet.js:5
_fireDOMEvent @ leaflet.js:5
_handleDOMEvent @ leaflet.js:5
o @ leaflet.js:5
OpenStreetMap2.js:481 Error: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

Additionally I can't find the `full screen Control` on the map although I have chosen the option.

**Comment by sfroemkenjw** [comment]
Good morning @Hobokens 

In URI I see following part `type=1614075471`. Since TYPO3 9 this can be a problem. Do you have configured `PageTypeSuffix` in your RouteEnhancer? If yes, I'm pretty sure you have defined some `map` there. Remember: With your first entry in that `map` section you deactivate all URIs containing a `type` parameter. You have to collect ALL possible type-mappings here, now.
The other way would be to remove all type-mappings from that RouteEnhancer.

Please keep me informed, if it works for you, now.

Stefan

**Comment by Hobokens** [comment]
Hi @sfroemkenjw ,

I have only a small routeEnhancer for news and maps2 without any `PageTypeSuffix`. When I remove all routeEnhancers I get the error message.

```
OpenStreetMap2.js:481 Error: SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
(anonym) @ OpenStreetMap2.js:481

```
This is the URL [https://tafel-hoechberg.de/lebensmittelausgabe](https://tafel-hoechberg.de/lebensmittelausgabe)

**Comment by sfroemkenjw** [comment]
Good morning @Hobokens 

I have just tested that again.

My link when opening infoWindowContent:
`https://typo312.ddev.site/extensions/maps2/point?tx_maps2_maps2%5Baction%5D=process&tx_maps2_maps2%5Bcontroller%5D=Ajax&tx_maps2_maps2%5Bmethod%5D=renderInfoWindowContent&type=1614075471&cHash=8db52d72161a1491ac381a4f9c02b246#url`

Tested on TYPO3 12.4.10
maps2: 11.0.0
Provider: OpenStreetMap

config.yaml
```
base: 'https://typo312.ddev.site/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: 'Stefans TYPO3 Page'
rootPageId: 1
websiteTitle: 'Stefans TYPO3 Page'
```

Value for `pageNotFoundOnCHashError`: true

It works for me. So, can you please send me further information like your config.yaml?

Have a cool start into the new week

Stefan
